Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "learningchef/centos65"
  c.vm.box_url = "learningchef/centos65"
  c.vm.hostname = "default-node2"
    c.ssh.username = "vagrant"
    c.ssh.password = "vagrant"
  c.ssh.insert_key = "false"
  c.vm.network(:private_network, {:ip=>"192.168.33.9"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.gui = true
  end
end
