---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: server
    driver:
      box: learningchef/centos65
      gui: true
      username: "vagrant"
      password: "vagrant"
      ssh:
        insert_key: false
      box_url: learningchef/centos65
      network:
      - ["private_network", {ip: "192.168.33.7"}]

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
